[project]
name = "team27app"
version = "0.1.0"
description = "Team 27 App in Streamlit"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "authlib>=1.8.0",
    "email-validator>=2.3.0",
    "httpx2>=2.13.0",
    "pydantic-mongo>=3.1.0",
    "pymongo>=4.18.1",
    "requests>=2.34.2",
    "st-social-media-links>=0.1.5",
    "streamlit>=1.63.0",
]

[dependency-groups]
dev = [
    "pyproject-pre-commit>=0.6.1",
    "ruff>=0.16.7",
    "ty>=0.0.81",
]

[tool.ruff]
line-length = 100

[[tool.mypy.overrides]]
module = [
    "st_social_media_links.*"
]
follow_untyped_imports = true

[tool.uv]
link-mode = "copy"
